# Question bank. One source of truth for the web page and the print packet.
# "q" is what the student sees. "a" is HTML, web page only, never printed.
# "lines" is how many answer lines the print worksheet gives the item.

BANK = {
"B": [
  {"q":"Which part concentrates the light into a cone aimed at the specimen?",
   "choices":["Ocular lens","Condenser","Iris diaphragm","Objective lens"],
   "a":"<p><strong>B. Condenser.</strong> It gathers the light coming up from the illuminator and focuses it through the specimen. Without it the light spreads and the image looks soft and low contrast.</p>","lines":1},
  {"q":"Which part controls how much light reaches the specimen, and therefore the contrast and depth of field?",
   "choices":["Light intensity control","Condenser","Iris diaphragm","Nosepiece"],
   "a":"<p><strong>C. Iris diaphragm.</strong> The intensity control changes brightness. The iris changes the width of the light cone, which is what actually changes contrast and depth of field. This is why closing the iris sharpens edges when turning the light down does not.</p>","lines":1},
  {"q":"Which lens produces the first magnified image of the specimen?",
   "choices":["Ocular lens","Objective lens","Condenser","Iris diaphragm"],
   "a":"<p><strong>B. Objective lens.</strong> It is closest to the specimen and forms the first image. The ocular then magnifies that image a second time. Two magnification steps is what compound means.</p>","lines":1},
  {"q":"You need to move the slide slightly to the left without losing focus. What do you use?",
   "a":"<p>The <strong>mechanical stage control knobs</strong>. They move the slide in two directions, smoothly and in tiny increments. Pushing the slide with a finger overshoots and can pop it out of the clips.</p>","lines":2},
  {"q":"Which focus knob is safe to use on the 40x objective, and why is the other one not?",
   "a":"<p>Only the <strong>fine focus knob</strong>. On 40x the objective sits very close to the coverslip, and the coarse knob moves the stage far enough in one turn to drive the lens into the slide. That cracks the slide and can damage the objective.</p>","lines":3},
  {"q":"Name the two parts you hold when you carry a microscope.",
   "a":"<p>One hand on the <strong>arm</strong>, the other hand under the <strong>base</strong>, held upright. Carried tilted, the oculars can slide out of the body tube and hit the floor.</p>","lines":2},
  {"q":"What does the revolving nosepiece do, and how should you turn it?",
   "a":"<p>It holds the objective lenses and rotates them into the light path. Turn it by the <strong>ridged edge of the turret</strong>, not by grabbing an objective barrel, which loosens the objective over time and throws off alignment.</p>","lines":3},
  {"q":"Your slide is in place but nothing at all comes into focus at any setting. What is the most likely cause?",
   "a":"<p>The slide is <strong>upside down</strong>. The coverslip has to face up, toward the objective. Objectives are designed to focus through a coverslip of a standard thickness, so with the glass slide on top the working distance is wrong.</p>","lines":2},
],

"C": [
  {"q":"Your oculars are 10x. What is the total magnification on the 4x, 10x, and 40x objectives?",
   "a":"<p><strong>40x, 100x, and 400x.</strong> Total magnification is objective power times ocular power.</p>","lines":2},
  {"q":"With 10x oculars and a 100x oil immersion objective, what is the total magnification?",
   "a":"<p><strong>1000x.</strong> 100 times 10.</p>","lines":1},
  {"q":"A scope gives 500x total with a 50x objective. What is the power of the ocular?",
   "a":"<p><strong>10x.</strong> 500 divided by 50.</p>","lines":1},
  {"q":"At 40x total magnification your field of view is 4.5 mm across. Roughly how wide is the field at 400x?",
   "a":"<p>About <strong>0.45 mm</strong>, which is 450 micrometers. Magnification went up 10 times, so the field width shrinks to one tenth. This is the single best reason to find and center your specimen on scanning power.</p>","lines":3},
  {"q":"You count about 24 cells across the field at 100x total. Roughly how many will you see across the field at 400x?",
   "a":"<p>About <strong>6</strong>. The magnification went up 4 times, so the field width drops to one quarter, and one quarter of 24 is 6.</p>","lines":2},
  {"q":"Name three things that get worse as you increase magnification.",
   "a":"<p>The <strong>field of view</strong> gets smaller, the image gets <strong>darker</strong>, and the <strong>depth of field</strong> gets shallower. You also have less working distance between the lens and the slide.</p>","lines":3},
],

"D": [
  {"q":"What is the basic meaning of resolution?",
   "choices":["How many times larger the created image is than the real object",
              "How far apart two points can be and still be seen as separate",
              "How close together two points can be and still be seen as separate",
              "How bright the image is at a given magnification"],
   "a":"<p><strong>C.</strong> Resolution is the smallest separation at which two points still read as two points instead of one blur. Choice A is magnification. The smaller the number, the better the resolution.</p>","lines":1},
  {"q":"What is the approximate limit of resolution of a light microscope, and what sets that limit?",
   "a":"<p>Roughly <strong>0.1 to 0.2 micrometers</strong>. The limit is set by the <strong>wavelength of visible light</strong>. You cannot resolve detail much finer than the wavelength you are using to look at it.</p>","lines":3},
  {"q":"What is empty magnification?",
   "a":"<p>Enlarging an image past the point where the optics can add any more detail. The picture gets bigger and no clearer, so you are just looking at a larger blur. It is the reason a claim of 2000x on a toy light microscope means nothing.</p>","lines":3},
  {"q":"True or false. A transmission electron microscope has both higher resolution and higher magnification than a light microscope.",
   "a":"<p><strong>True.</strong> Resolution improves from about 0.1 to 0.2 micrometers down to about 2 nanometers, and useful magnification goes up to roughly 150,000x. The resolution is the part that matters, because it is what makes the extra magnification worth having.</p>","lines":1},
],

"E": [
  {"q":"You put a new slide on and go straight to the 40x objective. The field is empty. What went wrong and what do you do?",
   "a":"<p>You skipped scanning power. At 400x the field is only a few tenths of a millimeter wide, so unless the specimen was already centered you are almost certainly looking at blank glass. <strong>Return to 4x, find the specimen, center it, then climb.</strong></p>","lines":3},
  {"q":"Your image is bright but flat, washed out, and edges are hard to see. What is the fix?",
   "a":"<p>You are overilluminated. <strong>Close the iris diaphragm</strong> until the detail sharpens, and lower the intensity if needed. Light microscopy is a contrast problem, not a brightness problem, and most of these specimens are nearly transparent to begin with.</p>","lines":3},
  {"q":"You switch from 10x to 40x and the image is nearly in focus already. What property is this, and which knob do you use now?",
   "a":"<p>The objectives are <strong>parfocal</strong>. Use the <strong>fine focus knob</strong> only. If you find yourself needing a lot of coarse focus after a switch, something is wrong, usually a slide that was not seated flat.</p>","lines":3},
  {"q":"When you rotate from 10x to 40x, your specimen disappears off to the side. What does this tell you?",
   "a":"<p>You did not center it. Objectives are <strong>parcentric</strong>, so whatever is in the middle at low power stays near the middle at high power, but only what was in the middle. Anything near the edge of the low power field falls outside the high power field entirely.</p>","lines":3},
  {"q":"Half of your field is dark, in a clean curved edge. What are the two likeliest causes?",
   "a":"<p>The <strong>objective is not clicked fully into position</strong> in the nosepiece, or the <strong>condenser is racked down or off center</strong> so the light cone is not filling the aperture. Check the click first.</p>","lines":3},
  {"q":"You see dark specks in the field. When you rotate the ocular, they rotate with it. Where is the dirt?",
   "a":"<p>On the <strong>ocular lens</strong>. Clean it with lens paper. If the specks had stayed still while the ocular turned but moved when you moved the slide, the dirt would be on the slide. If they stayed put through both, the dirt is on the objective or the condenser.</p>","lines":2},
  {"q":"Why do you raise the stage while watching from the side rather than through the oculars?",
   "a":"<p>Because through the oculars you cannot judge the gap between the lens and the coverslip, and you will run the objective into the slide before you see anything. Approach from the side, then focus by moving the stage <strong>away</strong> from the objective.</p>","lines":3},
  {"q":"List the shutdown steps for a lab scope in order.",
   "a":"<p>Rotate back to <strong>4x</strong>, <strong>lower the stage</strong>, <strong>remove and clean the slide</strong>, turn the <strong>light down to zero before switching off</strong>, wipe any <strong>immersion oil</strong> off the 100x lens, <strong>wrap the cord</strong>, and <strong>replace the dust cover</strong>.</p>","lines":4},
],

"F": [
  {"q":"Put the steps of slide preparation in order: clearing, dehydration, embedding, fixation, mounting, sectioning, staining.",
   "a":"<p><strong>Fixation, dehydration, clearing, embedding, sectioning, mounting, staining.</strong> Fix Dead Cells Every Single Monday Sharp.</p>","lines":3},
  {"q":"Which step slows the deterioration of the specimen?",
   "choices":["Fixation","Clearing","Embedding","Sectioning"],
   "a":"<p><strong>A. Fixation.</strong> It chemically halts the enzymes and microbes that would otherwise break the tissue down, and locks proteins in place so structure is preserved.</p>","lines":1},
  {"q":"Why does the tissue have to be dehydrated before it can be embedded?",
   "a":"<p>Because <strong>paraffin and water do not mix</strong>. If water is still in the tissue the wax cannot infiltrate it, and without support the tissue is too soft to cut into thin sections.</p>","lines":3},
  {"q":"What does clearing with xylene accomplish?",
   "a":"<p>Xylene mixes with <strong>both alcohol and paraffin</strong>, so it acts as the bridge between the dehydration step and the embedding step. It also makes the tissue transparent, which is where the name comes from.</p>","lines":3},
  {"q":"Which tool is used to cut very thin sections of tissue?",
   "choices":["TEM","SEM","Condenser","Dehydrator","Microtome"],
   "a":"<p><strong>E. Microtome.</strong> It cuts paraffin blocks into ribbons roughly 5 to 10 micrometers thick.</p>","lines":1},
  {"q":"Why does a section have to be that thin?",
   "a":"<p>Because a light microscope forms the image from light that passes <strong>through</strong> the specimen. Anything thicker blocks the light and stacks structures on top of each other so nothing resolves cleanly.</p>","lines":3},
  {"q":"Name two ways electron microscopy sample preparation differs from light microscopy preparation.",
   "a":"<p>Any two of: fixation uses <strong>glutaraldehyde and osmium tetroxide</strong> rather than formalin; the specimen is embedded in <strong>plastic</strong> rather than paraffin; sections are far thinner, around <strong>100 nanometers</strong>; stains are <strong>heavy metals</strong> such as uranyl acetate and lead citrate rather than colored dyes; SEM specimens are <strong>coated in gold</strong>.</p>","lines":4},
],

"G": [
  {"q":"In an H and E preparation, which dye stains the nucleus and what color does it produce?",
   "a":"<p><strong>Hematoxylin</strong>, a basic dye, which stains nuclei <strong>blue to purple</strong>. It binds DNA because DNA is acidic.</p>","lines":2},
  {"q":"A structure on your slide is bright pink. Which dye bound to it, and what does that suggest about the structure?",
   "a":"<p><strong>Eosin</strong>, an acidic dye. It binds basic structures, mainly proteins, so pink usually means cytoplasm, collagen, or other extracellular protein. The structure is described as <strong>acidophilic</strong> or eosinophilic.</p>","lines":3},
  {"q":"Define basophilic and give one example of a basophilic structure.",
   "a":"<p><strong>Basophilic</strong> means base loving, meaning the structure takes up basic dye and appears blue to purple. Examples: the <strong>nucleus</strong>, and rough endoplasmic reticulum in a cell that makes a lot of protein, because both are rich in nucleic acid.</p>","lines":3},
  {"q":"Why is a stain necessary at all?",
   "a":"<p>Untreated tissue is essentially <strong>colorless and transparent</strong>, so there is almost no contrast for your eye to work with. Stains bind selectively based on charge, so they create contrast and tell you something chemical about the structure at the same time.</p>","lines":3},
  {"q":"You need to tell collagen apart from smooth muscle in an artery wall. Which stain would you ask for and why?",
   "a":"<p>A <strong>trichrome stain</strong> such as Masson. It uses three dyes that partition differently, so collagen and muscle come out in clearly different colors. On H and E alone they can both look pink.</p>","lines":3},
],

"H": [
  {"q":"Which electron microscope produces a two dimensional image of the inside of a cell, and how does it do it?",
   "a":"<p>The <strong>transmission electron microscope</strong>. Electrons pass through an ultrathin section and are collected on the far side, so the image is built from what got through, the same logic as a light microscope but with electrons.</p>","lines":3},
  {"q":"Which electron microscope produces a three dimensional view of a surface?",
   "a":"<p>The <strong>scanning electron microscope</strong>. A focused beam sweeps across a gold coated surface, and scattered and emitted electrons are collected and assembled into a surface image with depth and shadow.</p>","lines":3},
  {"q":"You want to see the cristae inside a mitochondrion. TEM or SEM?",
   "a":"<p><strong>TEM.</strong> Cristae are internal membrane folds, so you need an image made from electrons that traveled through the organelle, not off its surface.</p>","lines":1},
  {"q":"You want to see the carpet of microvilli on the surface of an intestinal cell. TEM or SEM?",
   "a":"<p><strong>SEM.</strong> This is a surface texture question, and SEM is the surface instrument.</p>","lines":1},
  {"q":"Why is an SEM specimen coated in gold?",
   "a":"<p>Gold is electrically conductive and dense, so it <strong>scatters and emits electrons efficiently</strong> from the surface and stops charge building up on the specimen. Without the coating the signal is weak and the image distorts.</p>","lines":3},
],

"I": [
  {"q":"A blood vessel is cut across its short axis, and a second vessel is cut along its length. Describe how each one looks on the slide.",
   "a":"<p>The cross section is a <strong>ring or circle</strong> with a lumen in the middle and the wall layers arranged around it. The longitudinal section is <strong>two parallel bands</strong> of wall with the lumen running between them. Same structure, two very different pictures.</p>","lines":4},
  {"q":"A slide of simple columnar epithelium appears to have several layers of nuclei at different heights. Give two possible explanations.",
   "a":"<p>One, the section was cut <strong>obliquely</strong> through the sheet, so you are seeing through the thickness of the tissue at an angle and the nuclei stack visually. Two, it may genuinely be <strong>pseudostratified</strong> columnar epithelium, where every cell reaches the basement membrane but the nuclei sit at different heights. Check whether every cell touches the basement membrane.</p>","lines":4},
  {"q":"Why should you look at more than one slide of a given tissue before you decide you know it?",
   "a":"<p>Because any one slide shows one plane of section through one piece of tissue, with whatever tears, folds, and artifacts that block happened to have. Textbook images are chosen because they are ideal. Seeing several real examples teaches you the range of what the tissue actually looks like, which is what a practical exam asks you to recognize.</p>","lines":4},
  {"q":"Before you look through the oculars, what is worth doing with the slide, and what does it buy you?",
   "a":"<p>Hold it up to the light and look at it with your naked eye. You see the <strong>shape and position of the section</strong>, where the tissue is dense, and where the good area is, so you can put that spot over the stage aperture instead of hunting for it at magnification.</p>","lines":3},
]
}

TITLES = {
 "B":"What each part does",
 "C":"Magnification math",
 "D":"Resolution",
 "E":"Running the scope",
 "F":"Making the slide",
 "G":"Stains",
 "H":"Electron microscopy",
 "I":"Thinking in three dimensions",
}
