/* ============================================================
   BIO 004 gap-closing cards (all weeks).
   Concepts taught in the Week 1 to 8 lecture notes but not
   previously tested in the bank, limited to gaps that cards are
   the right vehicle for. Identification-only items (skull
   landmarks, named ligaments, the olives and massa intermedia,
   the surface regional terms) are delivered through the lab
   sprints and Match-up, not duplicated here.

   Format matches the base bank:
     { id, dok, q, a, options:[...4], correctIndex, explanation }
   Load order on the course site:
     course-content.js -> dok3-explain-why.js -> gap-cards.js
   Author: Dr. Sharilyn Rennie.
   ============================================================ */
(function(){
  var C = (typeof window !== "undefined") ? window.BIO004_COURSE_CONTENT : null;
  if (!C || !C.modules) return;
  var byId = {};
  C.modules.forEach(function(m){ (m.topics||[]).forEach(function(t){ byId[t.id] = t; }); });

  var ADD = {

    /* ===== WEEK 1: Body Cavities, the two untested abdominopelvic regions ===== */
    "t-body-cavities": [
      { id:"w1g-bc-1", dok:1, q:"Which of the nine abdominopelvic regions contains the cecum and appendix?", a:"The right iliac (inguinal) region.", options:["The hypogastric (pubic) region.","The right iliac (inguinal) region.","The right lumbar region.","The epigastric region."], correctIndex:1, explanation:"The right iliac, or inguinal, region is the lower-right box of the nine-region grid and overlies the cecum and appendix, which is why appendicitis pain settles there. The hypogastric region is lower-center, the right lumbar is middle-right, and the epigastric is upper-center." },
      { id:"w1g-bc-2", dok:1, q:"The sigmoid colon lies mainly in which of the nine abdominopelvic regions?", a:"The left iliac (inguinal) region.", options:["The left lumbar region.","The umbilical region.","The left iliac (inguinal) region.","The left hypochondriac region."], correctIndex:2, explanation:"The left iliac, or inguinal, region is the lower-left box of the grid and holds the sigmoid colon, a common site of diverticulitis. The left lumbar region is middle-left, the umbilical region is center, and the left hypochondriac region is upper-left." }
    ],

    /* ===== WEEK 1: Tissues, the two untested cell junctions ===== */
    "t-tissues": [
      { id:"w1g-ti-1", dok:1, q:"Which cell junction forms an adhesion belt of cadherins tied to actin filaments, usually just deep to the tight junctions?", a:"The adherens junction.", options:["The adherens junction.","The gap junction.","The hemidesmosome.","The tight junction."], correctIndex:0, explanation:"Adherens junctions use transmembrane cadherins linked internally to actin to form a continuous adhesion belt around the cell, sitting just below the tight junctions. Gap junctions are communicating channels, hemidesmosomes anchor a cell to the basement membrane, and tight junctions seal the gap between cells." },
      { id:"w1g-ti-2", dok:1, q:"Which junction anchors the basal surface of an epithelial cell to the underlying basement membrane?", a:"The hemidesmosome.", options:["The desmosome.","The hemidesmosome.","The gap junction.","The adherens junction."], correctIndex:1, explanation:"Hemidesmosomes resemble half a desmosome and rivet the base of an epithelial cell to the basement membrane beneath it. A full desmosome links two adjacent cells, a gap junction is a communicating channel, and an adherens junction forms an adhesion belt between cells." },
      { id:"w1g-ti-3", dok:2, q:"A desmosome and a hemidesmosome both use anchoring filaments, but what do they bind?", a:"A desmosome binds two adjacent cells; a hemidesmosome binds a cell to the basement membrane.", options:["A desmosome binds a cell to the basement membrane; a hemidesmosome binds two cells.","A desmosome binds two adjacent cells; a hemidesmosome binds a cell to the basement membrane.","Both bind a cell to the basement membrane.","Both bind two adjacent cells."], correctIndex:1, explanation:"A desmosome is a spot weld between two neighboring cells, while a hemidesmosome attaches the base of one cell to the basement membrane below it. That is why hemidesmosomes are found only on the basal surface, and desmosomes are found between cells throughout an epithelium." }
    ],

    /* ===== WEEK 1: Integumentary, holocrine secretion and the dermal macrophage ===== */
    "t-integumentary": [
      { id:"w1g-ig-1", dok:1, q:"Sebaceous glands release their oily product by which mode of secretion, in which the whole cell fills with product and ruptures?", a:"Holocrine secretion.", options:["Merocrine secretion.","Apocrine secretion.","Holocrine secretion.","Endocrine secretion."], correctIndex:2, explanation:"In holocrine secretion the entire cell fills with product and bursts, so the cell itself becomes the secretion; this is how sebaceous glands release sebum. Merocrine glands release product by exocytosis with no cell loss, apocrine glands pinch off the apex of the cell, and endocrine glands release hormones into the blood." },
      { id:"w1g-ig-2", dok:2, q:"An eccrine sweat gland and a sebaceous gland use different secretion modes. Which pairing is correct?", a:"The sweat gland is merocrine; the sebaceous gland is holocrine.", options:["The sweat gland is holocrine; the sebaceous gland is merocrine.","Both are merocrine.","The sweat gland is merocrine; the sebaceous gland is holocrine.","Both are holocrine."], correctIndex:2, explanation:"Eccrine sweat glands secrete by exocytosis with no loss of cell material, which is merocrine secretion. Sebaceous glands secrete by filling and rupturing whole cells, which is holocrine secretion. The two glands sit in the same skin but use opposite modes." },
      { id:"w1g-ig-3", dok:1, q:"Which immune cell patrols the dermis, engulfing bacteria and debris and helping activate the immune response?", a:"The macrophage.", options:["The macrophage.","The keratinocyte.","The melanocyte.","The fibroblast."], correctIndex:0, explanation:"Dermal macrophages are phagocytes that engulf pathogens and cellular debris and help trigger immune responses. Keratinocytes produce keratin, melanocytes produce the pigment melanin, and fibroblasts build the fibers and ground substance of the dermis." }
    ],

    /* ===== WEEK 2: Bone histology, the lamellae types ===== */
    "t-bone-histology": [
      { id:"w2g-bh-1", dok:1, q:"Which lamellae run around the entire inner and outer circumference of compact bone, deep to the periosteum and around the medullary cavity?", a:"Circumferential lamellae.", options:["Concentric lamellae.","Circumferential lamellae.","Interstitial lamellae.","Spongy trabeculae."], correctIndex:1, explanation:"Circumferential lamellae wrap around the whole circumference of the bone, just deep to the periosteum (external) and around the marrow cavity (internal), resisting twisting. Concentric lamellae ring a single osteon, interstitial lamellae are leftover fragments between osteons, and trabeculae are the struts of spongy bone." },
      { id:"w2g-bh-2", dok:1, q:"The incomplete lamellae wedged between intact osteons, left over from bone remodeling, are called what?", a:"Interstitial lamellae.", options:["Interstitial lamellae.","Concentric lamellae.","Circumferential lamellae.","Lacunae."], correctIndex:0, explanation:"Interstitial lamellae are fragments of old osteons that were partly resorbed during remodeling and now fill the space between newer osteons. Concentric lamellae form an intact osteon, circumferential lamellae wrap the whole bone, and lacunae are the small cavities that house osteocytes." },
      { id:"w2g-bh-3", dok:2, q:"On a slide you see complete rings around a central canal, partial fragments between those units, and sheets wrapping the bone's outer edge. Name the three lamellae in that order.", a:"Concentric, interstitial, then circumferential.", options:["Circumferential, interstitial, then concentric.","Concentric, interstitial, then circumferential.","Interstitial, concentric, then circumferential.","Concentric, circumferential, then interstitial."], correctIndex:1, explanation:"Rings around a central canal are the concentric lamellae of an osteon; the fragments between osteons are interstitial lamellae; the sheets around the bone's perimeter are circumferential lamellae. Reading them tells you the osteon, the remodeling history, and the outer reinforcement." }
    ],

    /* ===== WEEK 2: Articulations, the missing joint movements + ligament classification ===== */
    "t-articulations": [
      { id:"w2g-ar-1", dok:1, q:"Which movement brings a limb toward the midline of the body?", a:"Adduction.", options:["Abduction.","Adduction.","Circumduction.","Rotation."], correctIndex:1, explanation:"Adduction moves a limb toward the midline, the opposite of abduction, which moves it away. Circumduction traces a cone, and rotation turns a bone around its long axis." },
      { id:"w2g-ar-2", dok:1, q:"In which movement does the distal end of a limb trace a circle while the proximal end stays fixed?", a:"Circumduction.", options:["Rotation.","Circumduction.","Adduction.","Elevation."], correctIndex:1, explanation:"Circumduction sweeps the distal end of a limb in a circle, combining flexion, abduction, extension, and adduction in sequence so the limb outlines a cone. Rotation turns a bone on its axis, adduction moves toward the midline, and elevation lifts a part superiorly." },
      { id:"w2g-ar-3", dok:1, q:"Rotating the forearm so the palm faces posteriorly, or downward, is called what?", a:"Pronation.", options:["Supination.","Pronation.","Eversion.","Opposition."], correctIndex:1, explanation:"Pronation rotates the forearm so the radius crosses the ulna and the palm faces backward or down. Supination is the reverse, palm forward as in anatomical position. Eversion turns the sole outward, and opposition moves the thumb to the fingertips." },
      { id:"w2g-ar-4", dok:1, q:"Rotating the forearm so the palm faces anteriorly, as in anatomical position, is called what?", a:"Supination.", options:["Supination.","Pronation.","Inversion.","Retraction."], correctIndex:0, explanation:"Supination rotates the forearm so the palm faces forward or up and the radius and ulna lie parallel. Pronation is the opposite. Inversion turns the sole medially, and retraction pulls a part posteriorly." },
      { id:"w2g-ar-5", dok:1, q:"Lifting the foot so the toes point upward, decreasing the angle at the ankle, is which movement?", a:"Dorsiflexion.", options:["Plantar flexion.","Dorsiflexion.","Eversion.","Elevation."], correctIndex:1, explanation:"Dorsiflexion raises the foot toward the shin, as in standing on the heels. Plantar flexion is the opposite, pointing the toes down. Eversion turns the sole laterally, and elevation lifts a part superiorly." },
      { id:"w2g-ar-6", dok:1, q:"Pointing the toes downward, as when standing on tiptoe, is which movement?", a:"Plantar flexion.", options:["Dorsiflexion.","Inversion.","Plantar flexion.","Protraction."], correctIndex:2, explanation:"Plantar flexion depresses the foot so the toes point downward, increasing the ankle angle. Dorsiflexion is the opposite. Inversion turns the sole medially, and protraction moves a part anteriorly." },
      { id:"w2g-ar-7", dok:1, q:"Turning the sole of the foot to face medially, or inward, is which movement?", a:"Inversion.", options:["Eversion.","Inversion.","Supination.","Adduction."], correctIndex:1, explanation:"Inversion turns the sole of the foot inward, toward the midline. Eversion is the opposite, turning the sole outward. Supination is the analogous forearm term, and adduction moves a whole limb toward the midline." },
      { id:"w2g-ar-8", dok:1, q:"Turning the sole of the foot to face laterally, or outward, is which movement?", a:"Eversion.", options:["Eversion.","Inversion.","Pronation.","Abduction."], correctIndex:0, explanation:"Eversion turns the sole of the foot outward, away from the midline. Inversion is the opposite. Pronation is the analogous forearm term, and abduction moves a whole limb away from the midline." },
      { id:"w2g-ar-9", dok:1, q:"Lifting a body part superiorly, such as shrugging the shoulders, is which movement?", a:"Elevation.", options:["Depression.","Protraction.","Elevation.","Circumduction."], correctIndex:2, explanation:"Elevation moves a part superiorly, like raising the scapulae in a shrug or closing the jaw. Depression is the opposite, moving it inferiorly. Protraction moves a part anteriorly, and circumduction traces a cone." },
      { id:"w2g-ar-10", dok:1, q:"Moving a body part anteriorly in the horizontal plane, such as jutting the jaw forward, is which movement?", a:"Protraction.", options:["Retraction.","Protraction.","Elevation.","Rotation."], correctIndex:1, explanation:"Protraction glides a part forward in the horizontal plane, as in pushing the jaw or scapulae anteriorly. Retraction is the opposite, pulling it back. Elevation lifts a part up, and rotation turns a bone on its axis." },
      { id:"w2g-ar-11", dok:1, q:"Pulling a body part posteriorly in the horizontal plane, such as squaring the shoulders back, is which movement?", a:"Retraction.", options:["Protraction.","Depression.","Retraction.","Supination."], correctIndex:2, explanation:"Retraction draws a part backward in the horizontal plane, like pulling the scapulae together. Protraction is the opposite. Depression lowers a part, and supination rotates the forearm palm-up." },
      { id:"w2g-ar-12", dok:1, q:"Moving the thumb across the palm to touch the tips of the other fingers is which movement, unique to the saddle joint of the thumb?", a:"Opposition.", options:["Opposition.","Reposition.","Circumduction.","Abduction."], correctIndex:0, explanation:"Opposition moves the thumb across the palm to touch the fingertips, the movement that lets the hand grip, and it occurs at the saddle joint between the trapezium and the first metacarpal. Reposition returns the thumb, circumduction traces a cone, and abduction moves a digit away from the midline of the hand." },
      { id:"w2g-ar-13", dok:2, q:"A patient rolls the ankle so the sole turns inward, then a therapist turns it outward. Name the two movements in order.", a:"Inversion, then eversion.", options:["Eversion, then inversion.","Inversion, then eversion.","Pronation, then supination.","Dorsiflexion, then plantar flexion."], correctIndex:1, explanation:"Turning the sole inward is inversion; turning it outward is eversion. Pronation and supination are the forearm equivalents, and dorsiflexion and plantar flexion raise and lower the whole foot rather than turning the sole." },
      { id:"w2g-ar-14", dok:2, q:"Starting in anatomical position, you rotate the forearm so the palm faces the floor, then return it. Which sequence is correct?", a:"Pronation, then supination.", options:["Supination, then pronation.","Pronation, then supination.","Inversion, then eversion.","Protraction, then retraction."], correctIndex:1, explanation:"Anatomical position is already supinated, palm forward. Turning the palm to face the floor is pronation, and returning to palm-forward is supination. Inversion and eversion describe the foot, and protraction and retraction are horizontal-plane glides." },
      { id:"w2g-ar-15", dok:2, q:"Reaching the arm forward versus squaring the shoulders back describes which pair of scapular movements?", a:"Protraction, then retraction.", options:["Retraction, then protraction.","Elevation, then depression.","Protraction, then retraction.","Rotation, then circumduction."], correctIndex:2, explanation:"Reaching forward glides the scapula anteriorly, which is protraction; squaring the shoulders pulls it posteriorly, which is retraction. Shrugging and dropping the shoulders are elevation and depression, and neither action is a rotation." },
      { id:"w2g-ar-16", dok:1, q:"The cruciate ligaments lie inside the knee's joint capsule. Ligaments in this position are classified as what?", a:"Intracapsular ligaments.", options:["Extracapsular ligaments.","Intracapsular ligaments.","Periosteal ligaments.","Accessory tendons."], correctIndex:1, explanation:"Intracapsular ligaments sit inside the joint capsule, like the cruciate ligaments of the knee, though they are wrapped in synovial membrane. Extracapsular ligaments, such as the collateral ligaments, lie outside the capsule. The other two are not standard ligament categories." },
      { id:"w2g-ar-17", dok:2, q:"A collateral ligament reinforces the outside of a joint capsule while a cruciate ligament sits within it. How are these classified?", a:"The collateral is extracapsular; the cruciate is intracapsular.", options:["The collateral is intracapsular; the cruciate is extracapsular.","Both are extracapsular.","The collateral is extracapsular; the cruciate is intracapsular.","Both are intracapsular."], correctIndex:2, explanation:"Ligaments are grouped by position relative to the joint capsule. Collateral ligaments lie outside it and are extracapsular; cruciate ligaments lie inside it and are intracapsular. The classification predicts how each is reached surgically and how it tends to be injured." }
    ],

    /* ===== WEEK 7 (brain): basal nuclei and the functional cortical areas ===== */
    "t-cns-brain": [
      { id:"w7g-br-1", dok:1, q:"Which deep masses of gray matter, including the putamen and globus pallidus, help regulate the initiation and coordination of voluntary movement?", a:"The basal nuclei.", options:["The basal nuclei.","The thalamic nuclei.","The cerebellar peduncles.","The cranial nerve nuclei."], correctIndex:0, explanation:"The basal nuclei, also called the basal ganglia, are gray-matter masses deep in the cerebral white matter that help start and fine-tune voluntary movement and set muscle tone. The thalamic nuclei relay sensory traffic, the cerebellar peduncles connect the cerebellum, and cranial nerve nuclei serve the cranial nerves." },
      { id:"w7g-br-2", dok:1, q:"The putamen and the globus pallidus together form which structure of the basal nuclei?", a:"The lentiform nucleus.", options:["The caudate nucleus.","The lentiform nucleus.","The thalamus.","The red nucleus."], correctIndex:1, explanation:"The putamen and globus pallidus together make up the lens-shaped lentiform nucleus; the putamen plus the caudate nucleus make up the striatum. The thalamus and the red nucleus are separate gray-matter structures." },
      { id:"w7g-br-3", dok:2, q:"Degeneration of the basal nuclei underlies disorders such as Parkinson disease. What does that reveal about their normal job?", a:"They normally help initiate and smooth voluntary movement and regulate muscle tone.", options:["They normally produce cerebrospinal fluid.","They normally help initiate and smooth voluntary movement and regulate muscle tone.","They normally process incoming visual signals.","They normally set the rhythm of breathing."], correctIndex:1, explanation:"Parkinson disease causes tremor, rigidity, and slowed movement, which points to the basal nuclei's normal role in starting and smoothing voluntary movement and setting muscle tone. Cerebrospinal fluid is made by the choroid plexus, vision is processed in the occipital cortex, and breathing rhythm is set in the medulla." },
      { id:"w7g-br-4", dok:1, q:"Which cortical area, just anterior to the primary motor cortex, plans and coordinates learned, skilled, patterned movements?", a:"The premotor cortex.", options:["The primary motor cortex.","The premotor cortex.","The primary somatosensory cortex.","The prefrontal cortex."], correctIndex:1, explanation:"The premotor cortex sits just anterior to the primary motor cortex and stages skilled, patterned movements before the primary motor cortex executes them. The primary motor cortex sends the actual command, the somatosensory cortex receives touch, and the prefrontal cortex handles judgment and planning." },
      { id:"w7g-br-5", dok:1, q:"Which area on the medial surface of the frontal lobe helps plan complex, sequenced, and two-sided movements?", a:"The supplementary motor area.", options:["The supplementary motor area.","The primary gustatory cortex.","The Wernicke area.","The primary visual cortex."], correctIndex:0, explanation:"The supplementary motor area, on the medial frontal lobe, programs complex sequences and movements that involve both sides of the body. The gustatory cortex handles taste, the Wernicke area handles language comprehension, and the visual cortex processes sight." },
      { id:"w7g-br-6", dok:1, q:"Which region at the front of the frontal lobe governs judgment, reasoning, working memory, and personality?", a:"The prefrontal cortex.", options:["The prefrontal cortex.","The primary motor cortex.","The occipital cortex.","The premotor cortex."], correctIndex:0, explanation:"The prefrontal cortex, at the very front of the frontal lobe, is the seat of executive function: judgment, reasoning, planning, working memory, and personality. The primary motor cortex executes movement, the occipital cortex processes vision, and the premotor cortex stages skilled movement." },
      { id:"w7g-br-7", dok:1, q:"The primary gustatory cortex, which interprets the sense of taste, lies mainly in which region?", a:"The insula.", options:["The occipital lobe.","The insula.","The cerebellum.","The temporal pole."], correctIndex:1, explanation:"The primary gustatory cortex lies in the insula, the lobe buried deep to the lateral sulcus, and interprets taste. The occipital lobe handles vision, the cerebellum coordinates movement, and the temporal pole is not the taste area." }
    ]
  };

  Object.keys(ADD).forEach(function(id){
    var t = byId[id]; if (!t) return;
    t.cards = (t.cards||[]).concat(ADD[id]);
  });
})();
