/* ============================================================
   BIO 004 Human Anatomy, Fall 2026
   session-links.js

   Every class day, wired to the real material in this repo.

   WHY THIS FILE EXISTS
   --------------------
   bio004-course-calendar.html shipped with every pre-work link
   blank (l:""), so every day rendered "Link coming soon". The
   material was already here, 380 pages of it. Nothing was
   missing except the addresses.

   WHAT IS IN IT
   -------------
   Keyed by ISO date, one entry per class day, both tracks. The
   Tue/Thu day that teaches the same content as a Mon/Wed day
   carries the same material.

     worksheet  the pre-work sheet, worked FIRST with the notes
                and the reading open
     notes      her notes packets for that day, the reference the
                worksheet is worked against
     lecture    the concept video, watched AFTER the sheet
     slides     the lecture deck, for review after class
     lab        lab sprints for that day, in lab order
     exam       exam number, on exam days (no pre-work links)

   Holidays are absent on purpose. A date with no entry renders
   exactly as it did before, so a missing key is safe.

   EVERY FILENAME BELOW WAS CHECKED AGAINST THE REPO FILE LIST.
   None are guessed. If you rename a page, change it here and it
   changes on the calendar and every week page at once.
   ============================================================ */

window.BIO004_SESSION_LINKS = {
  "2026-08-17": { wk:1, sheets:[{u:"m1-intro-worksheet.html",t:"Intro to Anatomy"}], notes:[{u:"m1-intro-notes.html",t:"Intro to Anatomy"},{u:"m1-cavities-notes.html",t:"Body Cavities"}], workbooks:[{u:"anatomical-terminology-workbook.html",t:"Anatomical Terminology"},{u:"body-cavities-workbook.html",t:"Body Cavities and Regions"}], videos:[{u:"week1-concept-videos.html",t:"Foundations: The Language of Anatomy and Body Organization"}], slides:{u:"slides-foundations.html",t:"Foundations of Anatomy"}, lab:[{u:"lab-safety.html",t:"Lab Safety and Procedures"},{u:"body-cavities-lab-sprint.html",t:"Body Cavities and Regions"},{u:"anatomical-terminology-lab-sprint.html",t:"Anatomical Terminology"},{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-08-18": { wk:1, sheets:[{u:"m1-intro-worksheet.html",t:"Intro to Anatomy"}], notes:[{u:"m1-intro-notes.html",t:"Intro to Anatomy"},{u:"m1-cavities-notes.html",t:"Body Cavities"}], workbooks:[{u:"anatomical-terminology-workbook.html",t:"Anatomical Terminology"},{u:"body-cavities-workbook.html",t:"Body Cavities and Regions"}], videos:[{u:"week1-concept-videos.html",t:"Foundations: The Language of Anatomy and Body Organization"}], slides:{u:"slides-foundations.html",t:"Foundations of Anatomy"}, lab:[{u:"lab-safety.html",t:"Lab Safety and Procedures"},{u:"body-cavities-lab-sprint.html",t:"Body Cavities and Regions"},{u:"anatomical-terminology-lab-sprint.html",t:"Anatomical Terminology"},{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-08-19": { wk:1, sheets:[{u:"m1-cell-worksheet.html",t:"Cell Anatomy"}], notes:[{u:"m1-cell-notes.html",t:"Cell Anatomy"}], workbooks:[{u:"cell-anatomy-workbook.html",t:"Cell Anatomy"}], videos:[{u:"cell-concept-videos.html",t:"The Cell: Anatomy and Histology"}], slides:{u:"slides-cell-anatomy.html",t:"Cell Anatomy"}, lab:[{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-08-20": { wk:1, sheets:[{u:"m1-cell-worksheet.html",t:"Cell Anatomy"}], notes:[{u:"m1-cell-notes.html",t:"Cell Anatomy"}], workbooks:[{u:"cell-anatomy-workbook.html",t:"Cell Anatomy"}], videos:[{u:"cell-concept-videos.html",t:"The Cell: Anatomy and Histology"}], slides:{u:"slides-cell-anatomy.html",t:"Cell Anatomy"}, lab:[{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-08-24": { wk:2, sheets:[{u:"m1-cell-worksheet.html",t:"Cell Anatomy"}], notes:[{u:"m1-cell-notes.html",t:"Cell Anatomy"}], workbooks:[{u:"cell-anatomy-workbook.html",t:"Cell Anatomy"}], videos:[{u:"cell-concept-videos.html",t:"The Cell: Anatomy and Histology"}], slides:{u:"slides-cell-anatomy.html",t:"Cell Anatomy"}, lab:[{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-08-25": { wk:2, sheets:[{u:"m1-cell-worksheet.html",t:"Cell Anatomy"}], notes:[{u:"m1-cell-notes.html",t:"Cell Anatomy"}], workbooks:[{u:"cell-anatomy-workbook.html",t:"Cell Anatomy"}], videos:[{u:"cell-concept-videos.html",t:"The Cell: Anatomy and Histology"}], slides:{u:"slides-cell-anatomy.html",t:"Cell Anatomy"}, lab:[{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-08-26": { wk:2, sheets:[{u:"m1-tissues-worksheet.html",t:"Tissues"}], notes:[{u:"m1-tissues-notes.html",t:"Tissues"}], workbooks:[{u:"tissues-workbook.html",t:"Tissues and Histology"}], videos:[{u:"tissues-concept-videos.html",t:"Tissues and Histology"}], slides:{u:"slides-epithelial-tissue-classification.html",t:"Epithelial Tissue Classification"}, lab:[{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-08-27": { wk:2, sheets:[{u:"m1-tissues-worksheet.html",t:"Tissues"}], notes:[{u:"m1-tissues-notes.html",t:"Tissues"}], workbooks:[{u:"tissues-workbook.html",t:"Tissues and Histology"}], videos:[{u:"tissues-concept-videos.html",t:"Tissues and Histology"}], slides:{u:"slides-epithelial-tissue-classification.html",t:"Epithelial Tissue Classification"}, lab:[{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-08-31": { wk:3, sheets:[{u:"m1-tissues-worksheet.html",t:"Tissues"}], notes:[{u:"m1-tissues-notes.html",t:"Tissues"}], workbooks:[{u:"tissues-workbook.html",t:"Tissues and Histology"},{u:"nervous-tissue-workbook.html",t:"Nervous Tissue"}], videos:[{u:"tissues-concept-videos.html",t:"Tissues and Histology"},{u:"muscle-tissue-concept-videos.html",t:"Muscle Tissue & Microanatomy"},{u:"nervous-tissue-concept-videos.html",t:"Nervous Tissue"}], slides:{u:"slides-connective-tissues.html",t:"Connective Tissue"}, lab:[{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-09-01": { wk:3, sheets:[{u:"m1-tissues-worksheet.html",t:"Tissues"}], notes:[{u:"m1-tissues-notes.html",t:"Tissues"}], workbooks:[{u:"tissues-workbook.html",t:"Tissues and Histology"},{u:"nervous-tissue-workbook.html",t:"Nervous Tissue"}], videos:[{u:"tissues-concept-videos.html",t:"Tissues and Histology"},{u:"muscle-tissue-concept-videos.html",t:"Muscle Tissue & Microanatomy"},{u:"nervous-tissue-concept-videos.html",t:"Nervous Tissue"}], slides:{u:"slides-connective-tissues.html",t:"Connective Tissue"}, lab:[{u:"tissues-lab-sprint.html",t:"Tissues and Histology"}] },
  "2026-09-02": { wk:3, sheets:[{u:"m1-integumentary-worksheet.html",t:"Integumentary"}], notes:[{u:"m1-integumentary-notes.html",t:"Integumentary"}], workbooks:[{u:"integumentary-workbook.html",t:"Integumentary System"}], videos:[{u:"integumentary-concept-videos.html",t:"The Integumentary System"}], slides:{u:"slides-skin-structure.html",t:"Skin Structure"}, lab:[{u:"integumentary-lab-sprint.html",t:"Integumentary System"}] },
  "2026-09-03": { wk:3, sheets:[{u:"m1-integumentary-worksheet.html",t:"Integumentary"}], notes:[{u:"m1-integumentary-notes.html",t:"Integumentary"}], workbooks:[{u:"integumentary-workbook.html",t:"Integumentary System"}], videos:[{u:"integumentary-concept-videos.html",t:"The Integumentary System"}], slides:{u:"slides-skin-structure.html",t:"Skin Structure"}, lab:[{u:"integumentary-lab-sprint.html",t:"Integumentary System"}] },
  "2026-09-08": { wk:4, exam:1 },
  "2026-09-09": { wk:4, exam:1 },
  "2026-09-10": { wk:4, sheets:[{u:"m2-bone-worksheet.html",t:"Bone Tissue"}], notes:[{u:"m2-bone-notes.html",t:"Bone Tissue"}], workbooks:[{u:"bone-histology-workbook.html",t:"Bone Histology"}], videos:[{u:"bone-concept-videos.html",t:"Bone Tissue"},{u:"bone-tissue-video.html",t:"Bone Tissue"}], slides:{u:"slides-bone-tissue.html",t:"Bone Tissue"}, lab:[{u:"bone-histology-lab-sprint.html",t:"Bone Microanatomy"}] },
  "2026-09-14": { wk:5, sheets:[{u:"m2-bone-worksheet.html",t:"Bone Tissue"}], notes:[{u:"m2-bone-notes.html",t:"Bone Tissue"}], workbooks:[{u:"bone-histology-workbook.html",t:"Bone Histology"}], videos:[{u:"bone-concept-videos.html",t:"Bone Tissue"},{u:"bone-tissue-video.html",t:"Bone Tissue"}], slides:{u:"slides-bone-tissue.html",t:"Bone Tissue"}, lab:[{u:"bone-histology-lab-sprint.html",t:"Bone Microanatomy"}] },
  "2026-09-15": { wk:5, sheets:[{u:"m2-axial-worksheet.html",t:"Axial Skeleton"}], notes:[{u:"m2-skull-notes.html",t:"Skull"}], workbooks:[{u:"axial-skeleton-skull-workbook.html",t:"Axial Skeleton: Skull"}], videos:[{u:"axial-concept-videos.html",t:"Axial Skeleton"}], slides:{u:"slides-axial-skeleton.html",t:"Axial Skeleton"}, lab:[{u:"axial-skeleton-skull-lab-sprint.html",t:"Axial Skeleton: The Skull"}] },
  "2026-09-16": { wk:5, sheets:[{u:"m2-axial-worksheet.html",t:"Axial Skeleton"}], notes:[{u:"m2-skull-notes.html",t:"Skull"}], workbooks:[{u:"axial-skeleton-skull-workbook.html",t:"Axial Skeleton: Skull"}], videos:[{u:"axial-concept-videos.html",t:"Axial Skeleton"}], slides:{u:"slides-axial-skeleton.html",t:"Axial Skeleton"}, lab:[{u:"axial-skeleton-skull-lab-sprint.html",t:"Axial Skeleton: The Skull"}] },
  "2026-09-17": { wk:5, sheets:[{u:"m2-axial-worksheet.html",t:"Axial Skeleton"}], notes:[{u:"m2-spine-notes.html",t:"Spine and Thoracic Cage"}], workbooks:[{u:"axial-skeleton-spine-workbook.html",t:"Axial Skeleton: Spine"}], videos:[{u:"axial-concept-videos.html",t:"Axial Skeleton"}], slides:{u:"slides-axial-skeleton.html",t:"Axial Skeleton"}, lab:[{u:"axial-skeleton-spine-lab-sprint.html",t:"Axial Skeleton: Spine and Thoracic Cage"}] },
  "2026-09-21": { wk:6, sheets:[{u:"m2-axial-worksheet.html",t:"Axial Skeleton"}], notes:[{u:"m2-spine-notes.html",t:"Spine and Thoracic Cage"}], workbooks:[{u:"axial-skeleton-spine-workbook.html",t:"Axial Skeleton: Spine"}], videos:[{u:"axial-concept-videos.html",t:"Axial Skeleton"}], slides:{u:"slides-axial-skeleton.html",t:"Axial Skeleton"}, lab:[{u:"axial-skeleton-spine-lab-sprint.html",t:"Axial Skeleton: Spine and Thoracic Cage"}] },
  "2026-09-22": { wk:6, sheets:[{u:"m2-appendicular-worksheet.html",t:"Appendicular Skeleton"}], notes:[{u:"m2-bone-notes.html",t:"Bone Tissue"},{u:"m2-upper-limb-notes.html",t:"Upper Extremity"}], workbooks:[{u:"bone-histology-workbook.html",t:"Bone Histology"},{u:"appendicular-skeleton-upper-workbook.html",t:"Appendicular Skeleton. Upper Limb"}], videos:[{u:"bone-concept-videos.html",t:"Bone Tissue"},{u:"appendicular-concept-videos.html",t:"Appendicular Skeleton"}], slides:{u:"slides-bone-development-fractures.html",t:"Bone Development and Fractures"}, lab:[{u:"appendicular-skeleton-upper-lab-sprint.html",t:"Appendicular Skeleton: Upper Limb"}] },
  "2026-09-23": { wk:6, sheets:[{u:"m2-appendicular-worksheet.html",t:"Appendicular Skeleton"}], notes:[{u:"m2-bone-notes.html",t:"Bone Tissue"},{u:"m2-upper-limb-notes.html",t:"Upper Extremity"}], workbooks:[{u:"bone-histology-workbook.html",t:"Bone Histology"},{u:"appendicular-skeleton-upper-workbook.html",t:"Appendicular Skeleton. Upper Limb"}], videos:[{u:"bone-concept-videos.html",t:"Bone Tissue"},{u:"appendicular-concept-videos.html",t:"Appendicular Skeleton"}], slides:{u:"slides-bone-development-fractures.html",t:"Bone Development and Fractures"}, lab:[{u:"appendicular-skeleton-upper-lab-sprint.html",t:"Appendicular Skeleton: Upper Limb"}] },
  "2026-09-24": { wk:6, sheets:[{u:"m2-appendicular-worksheet.html",t:"Appendicular Skeleton"},{u:"m2-joints-worksheet.html",t:"Joints"}], notes:[{u:"m2-lower-limb-notes.html",t:"Lower Extremity"},{u:"m2-joints-notes.html",t:"Joints"}], workbooks:[{u:"appendicular-skeleton-lower-workbook.html",t:"Appendicular Skeleton. Lower Limb"},{u:"articulations-workbook.html",t:"Articulations"}], videos:[{u:"appendicular-concept-videos.html",t:"Appendicular Skeleton"},{u:"joints-concept-videos.html",t:"Joints"}], slides:{u:"slides-appendicular-skeleton.html",t:"Appendicular Skeleton"}, lab:[{u:"appendicular-skeleton-lower-lab-sprint.html",t:"Appendicular Skeleton: Lower Limb"}] },
  "2026-09-28": { wk:7, sheets:[{u:"m2-appendicular-worksheet.html",t:"Appendicular Skeleton"},{u:"m2-joints-worksheet.html",t:"Joints"}], notes:[{u:"m2-lower-limb-notes.html",t:"Lower Extremity"},{u:"m2-joints-notes.html",t:"Joints"}], workbooks:[{u:"appendicular-skeleton-lower-workbook.html",t:"Appendicular Skeleton. Lower Limb"},{u:"articulations-workbook.html",t:"Articulations"}], videos:[{u:"appendicular-concept-videos.html",t:"Appendicular Skeleton"},{u:"joints-concept-videos.html",t:"Joints"}], slides:{u:"slides-appendicular-skeleton.html",t:"Appendicular Skeleton"}, lab:[{u:"appendicular-skeleton-lower-lab-sprint.html",t:"Appendicular Skeleton: Lower Limb"}] },
  "2026-09-29": { wk:7, exam:2 },
  "2026-09-30": { wk:7, exam:2 },
  "2026-10-01": { wk:7, sheets:[{u:"m3-heart-worksheet.html",t:"Heart"}], notes:[{u:"m3-heart-notes.html",t:"Heart"},{u:"m3-conduction-notes.html",t:"Cardiac Conduction"},{u:"m3-vessels-notes.html",t:"Blood Vessels"}], workbooks:[{u:"heart-workbook.html",t:"The Heart"},{u:"cardiac-conduction-workbook.html",t:"Cardiac Conduction"},{u:"blood-vessels-workbook.html",t:"Blood Vessels"}], videos:[{u:"heart-concept-videos.html",t:"The Heart"},{u:"cardiac-conduction-concept-videos.html",t:"Cardiac Conduction"},{u:"blood-vessels-concept-videos.html",t:"Blood Vessels"}], slides:{u:"slides-heart-anatomy.html",t:"The Heart"}, lab:[{u:"heart-lab-sprint.html",t:"The Heart"},{u:"blood-vessels-lab-sprint.html",t:"Blood Vessels"},{u:"cardiac-conduction-lab-sprint.html",t:"Cardiac Conduction"}] },
  "2026-10-05": { wk:8, sheets:[{u:"m3-heart-worksheet.html",t:"Heart"}], notes:[{u:"m3-heart-notes.html",t:"Heart"},{u:"m3-conduction-notes.html",t:"Cardiac Conduction"},{u:"m3-vessels-notes.html",t:"Blood Vessels"}], workbooks:[{u:"heart-workbook.html",t:"The Heart"},{u:"cardiac-conduction-workbook.html",t:"Cardiac Conduction"},{u:"blood-vessels-workbook.html",t:"Blood Vessels"}], videos:[{u:"heart-concept-videos.html",t:"The Heart"},{u:"cardiac-conduction-concept-videos.html",t:"Cardiac Conduction"},{u:"blood-vessels-concept-videos.html",t:"Blood Vessels"}], slides:{u:"slides-heart-anatomy.html",t:"The Heart"}, lab:[{u:"heart-lab-sprint.html",t:"The Heart"},{u:"blood-vessels-lab-sprint.html",t:"Blood Vessels"},{u:"cardiac-conduction-lab-sprint.html",t:"Cardiac Conduction"}] },
  "2026-10-06": { wk:8, sheets:[{u:"m3-muscle-worksheet.html",t:"Muscle and Trunk and Limb Muscles"}], notes:[{u:"m3-muscle-notes.html",t:"Muscle Structure"},{u:"m3-fascicles-notes.html",t:"Fascicles and Levers"}], workbooks:[{u:"muscle-structure-workbook.html",t:"Muscle Microanatomy"},{u:"muscle-fascicles-workbook.html",t:"Muscle Fascicle Arrangements"}], videos:[{u:"muscle-structure-concept-videos.html",t:"Muscle Structure"},{u:"muscle-tissue-concept-videos.html",t:"Muscle Tissue & Microanatomy"},{u:"muscle-fascicles-concept-videos.html",t:"Muscle Fascicles & Levers"}], slides:{u:"slides-muscle-microanatomy.html",t:"Skeletal Muscle Microanatomy"}, lab:[{u:"muscle-structure-lab-sprint.html",t:"Muscle Microanatomy"}] },
  "2026-10-07": { wk:8, sheets:[{u:"m3-muscle-worksheet.html",t:"Muscle and Trunk and Limb Muscles"}], notes:[{u:"m3-muscle-notes.html",t:"Muscle Structure"},{u:"m3-fascicles-notes.html",t:"Fascicles and Levers"}], workbooks:[{u:"muscle-structure-workbook.html",t:"Muscle Microanatomy"},{u:"muscle-fascicles-workbook.html",t:"Muscle Fascicle Arrangements"}], videos:[{u:"muscle-structure-concept-videos.html",t:"Muscle Structure"},{u:"muscle-tissue-concept-videos.html",t:"Muscle Tissue & Microanatomy"},{u:"muscle-fascicles-concept-videos.html",t:"Muscle Fascicles & Levers"}], slides:{u:"slides-muscle-microanatomy.html",t:"Skeletal Muscle Microanatomy"}, lab:[{u:"muscle-structure-lab-sprint.html",t:"Muscle Microanatomy"}] },
  "2026-10-08": { wk:8, sheets:[{u:"m3-heart-worksheet.html",t:"Heart"}], notes:[{u:"m3-heart-notes.html",t:"Heart"},{u:"m3-back-thorax-notes.html",t:"Back and Thorax Muscles"}], workbooks:[{u:"heart-workbook.html",t:"The Heart"}], videos:[{u:"heart-concept-videos.html",t:"The Heart"},{u:"muscular-system-concept-videos.html",t:"Muscular System"}], slides:{u:"slides-heart-anatomy.html",t:"The Heart"}, lab:[{u:"head-neck-muscles-lab-sprint.html",t:"Head and Neck Muscles"},{u:"chest-anterior-brachium-muscles-lab-sprint.html",t:"Chest and Anterior Brachium Muscles"},{u:"posterior-thorax-shoulder-muscles-lab-sprint.html",t:"Posterior Thorax, Shoulder, and Posterior Brachium"}] },
  "2026-10-12": { wk:9, sheets:[{u:"m3-heart-worksheet.html",t:"Heart"}], notes:[{u:"m3-heart-notes.html",t:"Heart"},{u:"m3-back-thorax-notes.html",t:"Back and Thorax Muscles"}], workbooks:[{u:"heart-workbook.html",t:"The Heart"}], videos:[{u:"heart-concept-videos.html",t:"The Heart"},{u:"muscular-system-concept-videos.html",t:"Muscular System"}], slides:{u:"slides-heart-anatomy.html",t:"The Heart"}, lab:[{u:"head-neck-muscles-lab-sprint.html",t:"Head and Neck Muscles"},{u:"chest-anterior-brachium-muscles-lab-sprint.html",t:"Chest and Anterior Brachium Muscles"},{u:"posterior-thorax-shoulder-muscles-lab-sprint.html",t:"Posterior Thorax, Shoulder, and Posterior Brachium"}] },
  "2026-10-14": { wk:9, sheets:[{u:"m3-vessels-blood-worksheet.html",t:"Blood Vessels and Blood"}], notes:[{u:"m3-blood-notes.html",t:"Blood"},{u:"m3-arm-muscles-notes.html",t:"Upper Limb Muscles"}], workbooks:[{u:"blood-workbook.html",t:"Blood"}], videos:[{u:"blood-concept-videos.html",t:"Blood"},{u:"muscular-system-concept-videos.html",t:"Muscular System"}], slides:{u:"slides-blood.html",t:"Blood"}, lab:[{u:"chest-anterior-brachium-muscles-lab-sprint.html",t:"Chest and Anterior Brachium Muscles"},{u:"antebrachium-muscles-lab-sprint.html",t:"Antebrachium Muscles"}] },
  "2026-10-15": { wk:9, sheets:[{u:"m3-vessels-blood-worksheet.html",t:"Blood Vessels and Blood"}], notes:[{u:"m3-blood-notes.html",t:"Blood"},{u:"m3-arm-muscles-notes.html",t:"Upper Limb Muscles"}], workbooks:[{u:"blood-workbook.html",t:"Blood"}], videos:[{u:"blood-concept-videos.html",t:"Blood"},{u:"muscular-system-concept-videos.html",t:"Muscular System"}], slides:{u:"slides-blood.html",t:"Blood"}, lab:[{u:"chest-anterior-brachium-muscles-lab-sprint.html",t:"Chest and Anterior Brachium Muscles"},{u:"antebrachium-muscles-lab-sprint.html",t:"Antebrachium Muscles"}] },
  "2026-10-19": { wk:10, sheets:[{u:"m3-vessels-blood-worksheet.html",t:"Blood Vessels and Blood"},{u:"m3-limb-vessels-worksheet.html",t:"Upper Limb Vessels and Nerves"}], notes:[{u:"m3-blood-notes.html",t:"Blood"},{u:"m3-limb-vessels-notes.html",t:"Upper Limb Vessels and Nerves"},{u:"m3-vessel-disorders-notes.html",t:"Vessel Disorders and Fetal Circulation"}], workbooks:[{u:"blood-workbook.html",t:"Blood"},{u:"blood-vessels-workbook.html",t:"Blood Vessels"},{u:"blood-vessel-disorders-workbook.html",t:"Blood Vessel Disorders"}], videos:[{u:"blood-concept-videos.html",t:"Blood"},{u:"blood-vessels-concept-videos.html",t:"Blood Vessels"}], slides:{u:"slides-blood.html",t:"Blood"}, lab:[{u:"antebrachium-muscles-lab-sprint.html",t:"Antebrachium Muscles"}] },
  "2026-10-20": { wk:10, sheets:[{u:"m3-vessels-blood-worksheet.html",t:"Blood Vessels and Blood"},{u:"m3-limb-vessels-worksheet.html",t:"Upper Limb Vessels and Nerves"}], notes:[{u:"m3-blood-notes.html",t:"Blood"},{u:"m3-limb-vessels-notes.html",t:"Upper Limb Vessels and Nerves"},{u:"m3-vessel-disorders-notes.html",t:"Vessel Disorders and Fetal Circulation"}], workbooks:[{u:"blood-workbook.html",t:"Blood"},{u:"blood-vessels-workbook.html",t:"Blood Vessels"},{u:"blood-vessel-disorders-workbook.html",t:"Blood Vessel Disorders"}], videos:[{u:"blood-concept-videos.html",t:"Blood"},{u:"blood-vessels-concept-videos.html",t:"Blood Vessels"}], slides:{u:"slides-blood.html",t:"Blood"}, lab:[{u:"antebrachium-muscles-lab-sprint.html",t:"Antebrachium Muscles"}] },
  "2026-10-21": { wk:10, exam:3 },
  "2026-10-22": { wk:10, exam:3 },
  "2026-10-26": { wk:11, sheets:[{u:"m4-resp-worksheet.html",t:"Respiratory and Lymphatic"},{u:"m3-respiratory-worksheet.html",t:"Respiratory System"}], notes:[{u:"m4-respiratory-notes.html",t:"Respiratory System"},{u:"m3-respiratory-notes.html",t:"Respiratory System"}], workbooks:[{u:"respiratory-workbook.html",t:"Respiratory System"}], videos:[{u:"respiratory-concept-videos.html",t:"Respiratory System"}], slides:{u:"slides-respiratory-anatomy.html",t:"Respiratory Anatomy & Mechanics"}, lab:[{u:"respiratory-lab-sprint.html",t:"Respiratory System"}] },
  "2026-10-27": { wk:11, sheets:[{u:"m4-resp-worksheet.html",t:"Respiratory and Lymphatic"},{u:"m3-respiratory-worksheet.html",t:"Respiratory System"}], notes:[{u:"m4-respiratory-notes.html",t:"Respiratory System"},{u:"m3-respiratory-notes.html",t:"Respiratory System"}], workbooks:[{u:"respiratory-workbook.html",t:"Respiratory System"}], videos:[{u:"respiratory-concept-videos.html",t:"Respiratory System"}], slides:{u:"slides-respiratory-anatomy.html",t:"Respiratory Anatomy & Mechanics"}, lab:[{u:"respiratory-lab-sprint.html",t:"Respiratory System"}] },
  "2026-10-28": { wk:11, sheets:[{u:"m4-urinary-worksheet.html",t:"Urinary and Endocrine"}], notes:[{u:"m4-endocrine-notes.html",t:"Endocrine Anatomy"},{u:"m4-lymphatic-notes.html",t:"Lymphatic System"}], workbooks:[{u:"lymphatic-system-workbook.html",t:"Lymphatic System"},{u:"endocrine-workbook.html",t:"Endocrine System"}], videos:[{u:"endocrine-concept-videos.html",t:"Endocrine System"},{u:"lymphatic-concept-videos.html",t:"Lymphatic System"}], slides:{u:"slides-endocrine.html",t:"Endocrine System"}, lab:[{u:"thigh-muscles-lab-sprint.html",t:"Thigh Muscles"}] },
  "2026-10-29": { wk:11, sheets:[{u:"m4-urinary-worksheet.html",t:"Urinary and Endocrine"}], notes:[{u:"m4-endocrine-notes.html",t:"Endocrine Anatomy"},{u:"m4-lymphatic-notes.html",t:"Lymphatic System"}], workbooks:[{u:"lymphatic-system-workbook.html",t:"Lymphatic System"},{u:"endocrine-workbook.html",t:"Endocrine System"}], videos:[{u:"endocrine-concept-videos.html",t:"Endocrine System"},{u:"lymphatic-concept-videos.html",t:"Lymphatic System"}], slides:{u:"slides-endocrine.html",t:"Endocrine System"}, lab:[{u:"thigh-muscles-lab-sprint.html",t:"Thigh Muscles"}] },
  "2026-11-02": { wk:12, sheets:[{u:"m4-resp-worksheet.html",t:"Respiratory and Lymphatic"},{u:"m3-respiratory-worksheet.html",t:"Respiratory System"}], notes:[{u:"m4-respiratory-notes.html",t:"Respiratory System"},{u:"m4-lymphatic-notes.html",t:"Lymphatic System"},{u:"m3-respiratory-notes.html",t:"Respiratory System"}], workbooks:[{u:"respiratory-workbook.html",t:"Respiratory System"}], videos:[{u:"respiratory-concept-videos.html",t:"Respiratory System"}], slides:{u:"slides-respiratory-anatomy.html",t:"Respiratory Anatomy & Mechanics"}, lab:[{u:"thigh-muscles-lab-sprint.html",t:"Thigh Muscles"}] },
  "2026-11-03": { wk:12, sheets:[{u:"m4-resp-worksheet.html",t:"Respiratory and Lymphatic"},{u:"m3-respiratory-worksheet.html",t:"Respiratory System"}], notes:[{u:"m4-respiratory-notes.html",t:"Respiratory System"},{u:"m4-lymphatic-notes.html",t:"Lymphatic System"},{u:"m3-respiratory-notes.html",t:"Respiratory System"}], workbooks:[{u:"respiratory-workbook.html",t:"Respiratory System"}], videos:[{u:"respiratory-concept-videos.html",t:"Respiratory System"}], slides:{u:"slides-respiratory-anatomy.html",t:"Respiratory Anatomy & Mechanics"}, lab:[{u:"thigh-muscles-lab-sprint.html",t:"Thigh Muscles"}] },
  "2026-11-04": { wk:12, sheets:[{u:"m4-digest-worksheet.html",t:"Digestive System"}], notes:[{u:"m4-alimentary-notes.html",t:"Alimentary Canal"}], workbooks:[{u:"alimentary-canal-workbook.html",t:"Alimentary Canal"}], videos:[{u:"alimentary-concept-videos.html",t:"Alimentary Canal"},{u:"gi-concept-videos.html",t:"Digestive System"}], slides:{u:"slides-gi-alimentary-canal.html",t:"Alimentary Canal, Mouth to Anus"}, lab:[{u:"leg-muscles-lab-sprint.html",t:"Leg Muscles"}] },
  "2026-11-05": { wk:12, sheets:[{u:"m4-digest-worksheet.html",t:"Digestive System"}], notes:[{u:"m4-alimentary-notes.html",t:"Alimentary Canal"}], workbooks:[{u:"alimentary-canal-workbook.html",t:"Alimentary Canal"}], videos:[{u:"alimentary-concept-videos.html",t:"Alimentary Canal"},{u:"gi-concept-videos.html",t:"Digestive System"}], slides:{u:"slides-gi-alimentary-canal.html",t:"Alimentary Canal, Mouth to Anus"}, lab:[{u:"leg-muscles-lab-sprint.html",t:"Leg Muscles"}] },
  "2026-11-09": { wk:13, sheets:[{u:"m4-digest-worksheet.html",t:"Digestive System"}], notes:[{u:"m4-alimentary-notes.html",t:"Alimentary Canal"},{u:"m4-accessory-notes.html",t:"Accessory Digestive Organs"}], workbooks:[{u:"accessory-digestive-organs-workbook.html",t:"Accessory Digestive Organs"}], videos:[{u:"accessory-digestive-concept-videos.html",t:"Accessory Digestive Organs"},{u:"gi-concept-videos.html",t:"Digestive System"}], slides:{u:"slides-gi-accessory-structures.html",t:"GI Accessory Structures"}, lab:[{u:"alimentary-canal-lab-sprint.html",t:"Alimentary Canal"},{u:"accessory-digestive-organs-lab-sprint.html",t:"Accessory Digestive Organs"},{u:"abdominal-wall-lab-sprint.html",t:"Abdominal Wall and Peritoneal Cavity"}] },
  "2026-11-10": { wk:13, sheets:[{u:"m4-digest-worksheet.html",t:"Digestive System"}], notes:[{u:"m4-alimentary-notes.html",t:"Alimentary Canal"}], workbooks:[{u:"accessory-digestive-organs-workbook.html",t:"Accessory Digestive Organs"}], videos:[{u:"accessory-digestive-concept-videos.html",t:"Accessory Digestive Organs"},{u:"gi-concept-videos.html",t:"Digestive System"}], slides:{u:"slides-gi-accessory-structures.html",t:"GI Accessory Structures"}, lab:[{u:"alimentary-canal-lab-sprint.html",t:"Alimentary Canal"}] },
  "2026-11-12": { wk:13, sheets:[{u:"m4-digest-worksheet.html",t:"Digestive System"}], notes:[{u:"m4-accessory-notes.html",t:"Accessory Digestive Organs"}], workbooks:[{u:"alimentary-canal-workbook.html",t:"Alimentary Canal"},{u:"accessory-digestive-organs-workbook.html",t:"Accessory Digestive Organs"}], videos:[{u:"gi-concept-videos.html",t:"Digestive System"},{u:"alimentary-concept-videos.html",t:"Alimentary Canal"}], slides:{u:"slides-gi-anatomy.html",t:"Digestive Anatomy"}, lab:[{u:"accessory-digestive-organs-lab-sprint.html",t:"Accessory Digestive Organs"}] },
  "2026-11-16": { wk:14, exam:4 },
  "2026-11-17": { wk:14, exam:4 },
  "2026-11-18": { wk:14, sheets:[{u:"m4-urinary-worksheet.html",t:"Urinary and Endocrine"}], notes:[{u:"m4-urinary-notes.html",t:"Urinary System"}], workbooks:[{u:"urinary-system-workbook.html",t:"Urinary System"}], videos:[{u:"urinary-concept-videos.html",t:"Urinary System"}], slides:{u:"slides-renal-anatomy.html",t:"Renal Anatomy"}, lab:[{u:"urinary-system-lab-sprint.html",t:"Urinary System"}] },
  "2026-11-19": { wk:14, sheets:[{u:"m4-urinary-worksheet.html",t:"Urinary and Endocrine"}], notes:[{u:"m4-urinary-notes.html",t:"Urinary System"}], workbooks:[{u:"urinary-system-workbook.html",t:"Urinary System"}], videos:[{u:"urinary-concept-videos.html",t:"Urinary System"}], slides:{u:"slides-renal-anatomy.html",t:"Renal Anatomy"}, lab:[{u:"urinary-system-lab-sprint.html",t:"Urinary System"}] },
  "2026-11-23": { wk:15, sheets:[{u:"m4-repro-worksheet.html",t:"Reproductive System"},{u:"m4-review-worksheet.html",t:"Integration"}], notes:[{u:"m4-male-repro-notes.html",t:"Male Reproductive System"},{u:"m4-female-repro-notes.html",t:"Female Reproductive System"}], workbooks:[{u:"reproductive-female-workbook.html",t:"Female Reproductive System"},{u:"reproductive-male-workbook.html",t:"Male Reproductive System"}], videos:[{u:"reproductive-concept-videos.html",t:"Reproductive Systems"},{u:"reproductive-male-concept-videos.html",t:"Male Reproductive Anatomy"},{u:"reproductive-female-concept-videos.html",t:"Female Reproductive Anatomy"}], slides:{u:"slides-reproductive-systems.html",t:"Reproductive Systems"}, lab:[{u:"reproductive-male-lab-sprint.html",t:"Male Reproductive System"},{u:"reproductive-female-lab-sprint.html",t:"Female Reproductive System"}] },
  "2026-11-24": { wk:15, sheets:[{u:"m4-repro-worksheet.html",t:"Reproductive System"}], notes:[{u:"m4-male-repro-notes.html",t:"Male Reproductive System"},{u:"m4-female-repro-notes.html",t:"Female Reproductive System"}], workbooks:[{u:"reproductive-male-workbook.html",t:"Male Reproductive System"},{u:"reproductive-female-workbook.html",t:"Female Reproductive System"},{u:"urinary-system-workbook.html",t:"Urinary System"}], videos:[{u:"urinary-concept-videos.html",t:"Urinary System"},{u:"reproductive-male-concept-videos.html",t:"Male Reproductive Anatomy"},{u:"reproductive-female-concept-videos.html",t:"Female Reproductive Anatomy"}], slides:{u:"slides-kidney-anatomy-gfr.html",t:"Kidney Anatomy & Glomerular Filtration"}, lab:[{u:"reproductive-male-lab-sprint.html",t:"Male Reproductive System"},{u:"reproductive-female-lab-sprint.html",t:"Female Reproductive System"}] },
  "2026-11-30": { wk:16, sheets:[{u:"m5-cord-worksheet.html",t:"Meninges, CSF, and Spinal Cord"},{u:"m5-tissue-worksheet.html",t:"Nervous Tissue and Integration"}], notes:[{u:"m5-nervous-tissue-notes.html",t:"Nervous Tissue"},{u:"m5-brain-notes.html",t:"Brain"},{u:"m5-meninges-notes.html",t:"Meninges and CSF"}], workbooks:[{u:"cns-brain-workbook.html",t:"The Brain"},{u:"cns-meninges-csf-workbook.html",t:"Meninges and CSF"},{u:"neuronal-integration-workbook.html",t:"Neuronal Integration"},{u:"urinary-system-workbook.html",t:"Urinary System"}], videos:[{u:"urinary-concept-videos.html",t:"Urinary System"},{u:"brain-meninges-concept-videos.html",t:"CNS, Brain, CSF & Meninges"},{u:"brain-concept-videos.html",t:"The Brain"},{u:"meninges-concept-videos.html",t:"Meninges & CSF"}], slides:{u:"slides-renal-anatomy.html",t:"Renal Anatomy"}, lab:[{u:"cns-meninges-csf-lab-sprint.html",t:"Meninges, Ventricles, and CSF"}] },
  "2026-12-01": { wk:16, sheets:[{u:"m5-cord-worksheet.html",t:"Meninges, CSF, and Spinal Cord"},{u:"m5-tissue-worksheet.html",t:"Nervous Tissue and Integration"}], notes:[{u:"m5-nervous-tissue-notes.html",t:"Nervous Tissue"},{u:"m5-brain-notes.html",t:"Brain"},{u:"m5-meninges-notes.html",t:"Meninges and CSF"}], workbooks:[{u:"cns-brain-workbook.html",t:"The Brain"},{u:"cns-meninges-csf-workbook.html",t:"Meninges and CSF"},{u:"neuronal-integration-workbook.html",t:"Neuronal Integration"},{u:"urinary-system-workbook.html",t:"Urinary System"}], videos:[{u:"urinary-concept-videos.html",t:"Urinary System"},{u:"brain-meninges-concept-videos.html",t:"CNS, Brain, CSF & Meninges"},{u:"brain-concept-videos.html",t:"The Brain"},{u:"meninges-concept-videos.html",t:"Meninges & CSF"}], slides:{u:"slides-renal-anatomy.html",t:"Renal Anatomy"}, lab:[{u:"cns-meninges-csf-lab-sprint.html",t:"Meninges, Ventricles, and CSF"}] },
  "2026-12-02": { wk:16, sheets:[{u:"m5-brain-worksheet.html",t:"Brain and Brainstem"}], notes:[{u:"m5-brainstem-notes.html",t:"Brainstem"},{u:"m5-cranial-notes.html",t:"Cranial Nerves"},{u:"m5-integration-notes.html",t:"Neuronal Integration"}], workbooks:[{u:"cns-brainstem-workbook.html",t:"The Brainstem"},{u:"cranial-nerves-workbook.html",t:"Cranial Nerves"}], videos:[{u:"cranial-nerves-concept-videos.html",t:"Cranial Nerves"},{u:"brainstem-concept-videos.html",t:"The Brainstem"}], slides:{u:"slides-cranial-nerves.html",t:"Cranial Nerves & the Brain Stem"}, lab:[{u:"cns-brainstem-lab-sprint.html",t:"The Brainstem"},{u:"cranial-nerves-lab-sprint.html",t:"Cranial Nerves"}] },
  "2026-12-03": { wk:16, sheets:[{u:"m5-brain-worksheet.html",t:"Brain and Brainstem"}], notes:[{u:"m5-brainstem-notes.html",t:"Brainstem"},{u:"m5-cranial-notes.html",t:"Cranial Nerves"},{u:"m5-integration-notes.html",t:"Neuronal Integration"}], workbooks:[{u:"cns-brainstem-workbook.html",t:"The Brainstem"},{u:"cranial-nerves-workbook.html",t:"Cranial Nerves"}], videos:[{u:"cranial-nerves-concept-videos.html",t:"Cranial Nerves"},{u:"brainstem-concept-videos.html",t:"The Brainstem"}], slides:{u:"slides-cranial-nerves.html",t:"Cranial Nerves & the Brain Stem"}, lab:[{u:"cns-brainstem-lab-sprint.html",t:"The Brainstem"},{u:"cranial-nerves-lab-sprint.html",t:"Cranial Nerves"}] },
  "2026-12-07": { wk:17, sheets:[{u:"m5-pns-worksheet.html",t:"Peripheral and Autonomic"},{u:"m5-review-worksheet.html",t:"Integration"}], notes:[{u:"m5-cord-notes.html",t:"Spinal Cord"},{u:"m5-plexus-notes.html",t:"Nerve Plexuses"},{u:"m5-pns-notes.html",t:"Peripheral Nervous System"},{u:"m5-ans-notes.html",t:"Autonomic Nervous System"}], workbooks:[{u:"cns-spinal-cord-workbook.html",t:"The Spinal Cord"},{u:"nerve-plexuses-workbook.html",t:"Spinal Nerve Plexuses"},{u:"pns-workbook.html",t:"Peripheral Nervous System"},{u:"ans-workbook.html",t:"Autonomic Nervous System"},{u:"cranial-nerves-workbook.html",t:"Cranial Nerves"}], videos:[{u:"cranial-nerves-concept-videos.html",t:"Cranial Nerves"},{u:"spinal-pns-concept-videos.html",t:"Spinal Cord, Nerves & PNS"},{u:"spinal-cord-concept-videos.html",t:"Spinal Cord"},{u:"pns-concept-videos.html",t:"Peripheral Nervous System"},{u:"ans-concept-videos.html",t:"Autonomic Nervous System"}], slides:{u:"slides-cranial-nerves.html",t:"Cranial Nerves & the Brain Stem"}, lab:[{u:"cns-spinal-cord-lab-sprint.html",t:"Spinal Cord"},{u:"nerve-plexuses-lab-sprint.html",t:"Spinal Nerves and Plexuses"}] },
  "2026-12-08": { wk:17, sheets:[{u:"m5-pns-worksheet.html",t:"Peripheral and Autonomic"},{u:"m5-review-worksheet.html",t:"Integration"}], notes:[{u:"m5-cord-notes.html",t:"Spinal Cord"},{u:"m5-plexus-notes.html",t:"Nerve Plexuses"},{u:"m5-pns-notes.html",t:"Peripheral Nervous System"},{u:"m5-ans-notes.html",t:"Autonomic Nervous System"}], workbooks:[{u:"cns-spinal-cord-workbook.html",t:"The Spinal Cord"},{u:"nerve-plexuses-workbook.html",t:"Spinal Nerve Plexuses"},{u:"pns-workbook.html",t:"Peripheral Nervous System"},{u:"ans-workbook.html",t:"Autonomic Nervous System"},{u:"cranial-nerves-workbook.html",t:"Cranial Nerves"}], videos:[{u:"cranial-nerves-concept-videos.html",t:"Cranial Nerves"},{u:"spinal-pns-concept-videos.html",t:"Spinal Cord, Nerves & PNS"},{u:"spinal-cord-concept-videos.html",t:"Spinal Cord"},{u:"pns-concept-videos.html",t:"Peripheral Nervous System"},{u:"ans-concept-videos.html",t:"Autonomic Nervous System"}], slides:{u:"slides-cranial-nerves.html",t:"Cranial Nerves & the Brain Stem"}, lab:[{u:"cns-spinal-cord-lab-sprint.html",t:"Spinal Cord"},{u:"nerve-plexuses-lab-sprint.html",t:"Spinal Nerves and Plexuses"}] },
  "2026-12-09": { wk:17, exam:5 },
  "2026-12-10": { wk:17, exam:5 } };
