/* Build bio005-exam-bank.js from the card bank plus cards/exam/week-NN.json.
   Run: node tools/build_exam_bank.js
   Never hand edit the output. */
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
global.window = {};
require(path.join(root, 'bio005-competencies.js'));
require(path.join(root, 'os/bio005-card-bank.js'));
require(path.join(root, 'bio005-schedule-fall2026.js'));

const COMP = {};
window.BIO005_COMPETENCIES.forEach(c => COMP[c.id] = c);
const weeks = window.BIO005_WEEKS.map(w => ({ n: w.wk, title: w.title, opens: w.opens }));

const clean = s => String(s).replace(/\s*[—–]\s*/g, ', ').replace(/\s+/g, ' ').trim();

const items = [];
let cards = 0, skipped = 0;
window.BIO005_CARD_BANK.modules.forEach(m => m.topics.forEach(t => t.cards.forEach(c => {
  const comp = COMP[c.competencyId];
  if (!comp || !Array.isArray(c.options) || c.options.length < 3) { skipped++; return; }
  cards++;
  items.push({
    id: c.id, type: 'mc', competencyId: c.competencyId, week: comp.week, topic: comp.general,
    dok: c.dok || comp.dok || 2,
    stem: clean(c.q), options: c.options.map(clean), correct: c.correctIndex,
    why: clean(c.explanation || c.a || '')
  });
})));

const dir = path.join(root, 'cards/exam');
let authored = 0;
fs.readdirSync(dir).filter(f => /^week-\d\d\.json$/.test(f)).sort().forEach(f => {
  JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')).forEach(it => {
    const comp = COMP[it.competencyId];
    if (!comp) throw new Error(f + ': unknown competency ' + it.competencyId);
    const out = Object.assign({}, it, { week: comp.week, topic: comp.general });
    ['stem', 'case', 'statement', 'correction', 'why', 'prompt'].forEach(k => { if (out[k]) out[k] = clean(out[k]); });
    ['options', 'whyNot', 'rubric'].forEach(k => { if (out[k]) out[k] = out[k].map(clean); });
    items.push(out); authored++;
  });
});

const competencies = window.BIO005_COMPETENCIES.map(c => ({
  id: c.id, week: c.week, topic: c.general, name: c.name, can: c.can, dok: c.dok
}));

const perWeek = {}; const perType = {}; const perDok = {};
items.forEach(i => { perWeek[i.week] = (perWeek[i.week] || 0) + 1; perType[i.type] = (perType[i.type] || 0) + 1; perDok[i.dok] = (perDok[i.dok] || 0) + 1; });

const header = `/* ============================================================
   BIO 005 Human Physiology, Fall 2026
   bio005-exam-bank.js

   GENERATED by tools/build_exam_bank.js. Do not hand edit.
   Sources: os/bio005-card-bank.js (multiple choice) and
   cards/exam/week-NN.json (multiple answer, true or false with
   correction, brain dump, application). See EXAM-BANK-SPEC.md.

   ${items.length} items (${cards} multiple choice from the card bank, ${authored} authored).
   Per week: ${JSON.stringify(perWeek)}
   Per type: ${JSON.stringify(perType)}
   Per DOK:  ${JSON.stringify(perDok)}
   Built ${new Date().toISOString().slice(0, 10)}.
   ============================================================ */
`;
const bank = { built: new Date().toISOString().slice(0, 10), weeks, competencies, items };
fs.writeFileSync(path.join(root, 'bio005-exam-bank.js'), header + 'window.BIO005_EXAM_BANK = ' + JSON.stringify(bank) + ';\n');
console.log('items', items.length, 'cards', cards, 'skipped', skipped, 'authored', authored);
console.log('per week', perWeek); console.log('per type', perType); console.log('per dok', perDok);
